---
galaxy_info:
  author: Matthew Taylor
  description: Populates an Ansible Automation Platform instance.
  company: Red Hat
  license: GPL-3.0-only
  min_ansible_version: 2.15.0
  galaxy_tags: []
dependencies: []
...
