---
- name: gather_networks | Gather all registered dvswitch
  community.vmware.vmware_dvswitch_info:
    hostname: "{{ network_mgmt_vcenter_hostname }}"
    username: "{{ network_mgmt_vcenter_username }}"
    password: "{{ network_mgmt_vcenter_password }}"
    validate_certs: false
  delegate_to: localhost
  register: dvswitch_info

- name: gather_networks | Get info for all dVSwitch Port Groups
  community.vmware.vmware_dvs_portgroup_info:
    hostname: "{{ network_mgmt_vcenter_hostname }}"
    username: "{{ network_mgmt_vcenter_username }}"
    password: "{{ network_mgmt_vcenter_password }}"
    datacenter: "{{ network_mgmt_vcenter_datacenter }}"
    validate_certs: false
    show_vlan_info: true
  register: dvpg_info
...
