---

- name: _verify_operation | Verify VMs
  kubernetes.core.k8s_info:
    api_key: "{{ vm_lifecycle_openshift_api_key }}"
    host: "{{ vm_lifecycle_openshift_host }}"
    api_version: "{{ vm_lifecycle_kubevirt_api_version }}"
    kind: VirtualMachine
    namespace: "{{ vm_operations_vm.vm.metadata.namespace }}"
    name: "{{ vm_operations_vm.vm.metadata.name }}"
    validate_certs: "{{ vm_lifecycle_openshift_verify_ssl }}"
  register: vm_operation_status
  retries: "{{ vm_lifecycle_verify_retries }}"
  delay: "{{ vm_lifecycle_verify_delay }}"
  until:
    - vm_operation_status is defined
    - vm_operation_status.resources is defined
    - vm_operation_status.resources | length > 0
    - vm_operation_status.resources[0].status is defined
    - vm_operation_status.resources[0].status.printableStatus is defined
    - vm_operation_status.resources[0].status.printableStatus == vm_lifecycle_valid_vm_operations[vm_operations_vm['operation']].status # noqa: yaml[line-length]
    - "'ready' not in vm_lifecycle_valid_vm_operations[vm_operations_vm['operation']] or ('ready' in vm_operation_status.resources[0].status and vm_operation_status.resources[0].status.ready|bool)" # noqa: yaml[line-length]
...
