---
- name: _build_credentials | Create migration factory api token for {{ _mf_host }}
  when: "hostvars[_mf_host]['openshift_api_key'] is undefined"
  ansible.builtin.include_role:
    name: infra.openshift_virtualization_migration.create_mf_aap_token
  vars:
    openshift_host: "{{ hostvars[_mf_host]['openshift_host'] }}"
    openshift_username: "{{ hostvars[_mf_host]['openshift_username'] | default(None) }}"
    openshift_password: "{{ hostvars[_mf_host]['openshift_password'] | default(None) }}"
    openshift_temporary_api_key: "{{ hostvars[_mf_host]['openshift_temporary_api_key'] | default(None) }}"
    openshift_verify_ssl: "{{ hostvars[_mf_host]['openshift_verify_ssl'] | default(true) }}"

- name: _build_credentials | Set openshift_api_key var on {{ _mf_host }}
  when: "hostvars[_mf_host]['openshift_api_key'] is undefined"
  ansible.builtin.set_fact:
    openshift_api_key: "{{ openshift_api_key }}"
  delegate_to: "{{ _mf_host }}"
  delegate_facts: true
  no_log: "{{ aap_seed_secure_logging }}"

- name: _build_credentials | Build migration targets
  when: _mf_host in groups['migration_spoke']
  ansible.builtin.set_fact:
    _cluster_migration_targets: "{{ (hostvars[_mf_host]['migration_targets'] | selectattr('name', 'in', hostvars[_mf_host]['configured_migration_targets'])) | list }}" # noqa: yaml[line-length]
  no_log: "{{ aap_seed_secure_logging }}"

- name: _build_credentials | Build Migration Factory CaC Credential for {{ _mf_host }}
  when: _mf_host in groups['migration_spoke']
  ansible.builtin.set_fact:
    controller_credentials: "{{ controller_credentials + [lookup('template', 'openshift_virtualization_migration_cac.yml.j2') | ansible.builtin.from_yaml] }}" # noqa: yaml[line-length]
  no_log: "{{ aap_seed_secure_logging }}"

- name: _build_credentials | Build kubeconfig for {{ _mf_host }}
  ansible.builtin.set_fact:
    controller_credentials: "{{ controller_credentials + [lookup('template', 'kubeconfig.yml.j2') | ansible.builtin.from_yaml] }}" # noqa: yaml[line-length]
  no_log: "{{ aap_seed_secure_logging }}"
...
