---
- name: workflows | Set workflow variables
  ansible.builtin.set_fact:
    controller_workflows: []
    _mtv_workflow_names: []

- name: workflows | Build Operator Workflows
  ansible.builtin.set_fact:
    controller_workflows: "{{ controller_workflows + [lookup('template', 'operator_workflow.yml.j2') | ansible.builtin.from_yaml] }}" # noqa: yaml[line-length]

- name: workflows | Build MTV Target Workflows
  ansible.builtin.include_tasks: _mtv_workflow_job_templates.yml
  loop: "{{ groups['migration_spoke'] }}"
  loop_control:
    loop_var: _mf_host

- name: workflows | Build MTV Worklfow
  ansible.builtin.set_fact:
    controller_workflows: "{{ controller_workflows + [lookup('template', 'mtv_workflow.yml.j2') | ansible.builtin.from_yaml] }}" # noqa: yaml[line-length]

- name: workflows | Build Migration Factory Worklfow
  ansible.builtin.set_fact:
    controller_workflows: "{{ controller_workflows + [lookup('template', 'migration_factory_configuration_workflow.yml.j2') | ansible.builtin.from_yaml] }}" # noqa: yaml[line-length]
...
