---

- name: _snapshot_vm | Create Snapshot
  redhat.openshift.k8s:
    state: present
    api_key: "{{ vm_backup_restore_openshift_api_key }}"
    host: "{{ vm_backup_restore_openshift_host }}"
    validate_certs: "{{ vm_backup_restore_openshift_verify_ssl }}"
    definition:
      apiVersion: "{{ vm_backup_restore_snapshot_kubevirt_api_version }}"
      kind: VirtualMachineSnapshot
      metadata:
        generateName: "{{ vm_backup.response_obj.metadata.name }}-"
        namespace: "{{ vm_backup.response_obj.metadata.namespace }}"
        ownerReferences:
          - apiVersion: kubevirt.io/v1
            blockOwnerDeletion: false
            kind: VirtualMachine
            name: "{{ vm_backup.response_obj.metadata.name }}"
            uid: "{{ vm_backup.response_obj.metadata.uid }}"
      spec:
        source:
          apiGroup: kubevirt.io
          kind: VirtualMachine
          name: "{{ vm_backup.response_obj.metadata.name }}"
    wait: true
    wait_timeout: "{{ vm_backup_restore_vm_snapshot_wait_timeout }}"
    wait_condition:
      type: Ready
  register: snapshot_vm_result

- name: _snapshot_vm | Print Snapshot Name
  ansible.builtin.debug:
    msg: "Snapshot Created: Namespace: {{ snapshot_vm_result.result.metadata.namespace }} - Name: {{ snapshot_vm_result.result.metadata.name }}" # noqa: yaml[line-length]
...
