---
# tasks file for vm_backup_restore

- name: vm_backup | Verify OpenShift Connectivity Details Provided
  ansible.builtin.assert:
    that:
      - vm_backup_restore_openshift_host | default("", true) | length > 0
      - vm_backup_restore_openshift_api_key | default("", true) | length > 0
    quiet: true
    fail_msg: OpenShift Connectivity Details Not Provided

- name: vm_backup | Initialize Variables
  ansible.builtin.set_fact:
    vm_backup_vms: []

- name: vm_backup | Invoke Collect VM Role
  ansible.builtin.include_role:
    name: infra.openshift_virtualization_migration.vm_collect
  vars:
    vm_collect_openshift_api_key: "{{ vm_backup_restore_openshift_api_key }}"
    vm_collect_openshift_host: "{{ vm_backup_restore_openshift_host }}"
    vm_collect_verify_ssl: "{{ vm_backup_restore_openshift_verify_ssl }}"
    vm_collect_vms_var: vm_backup_vms
  loop: "{{ vm_backup_restore_request | selectattr('operation', 'equalto', 'snapshot') | list }}"
  loop_control:
    loop_var: "vm_collect_request_instance"

- name: vm_backup | Snapshot VMs'
  ansible.builtin.include_tasks:
    file: _snapshot_vm.yml
  loop: "{{ vm_backup_vms }}"
  loop_control:
    loop_var: vm_backup
    label: "Namespace: {{ vm_backup.response_obj.metadata.namespace }} - Name: {{ vm_backup.response_obj.metadata.name }}" # noqa: yaml[line-length]
...
