---

- name: _migrations | Template Migrations
  ansible.builtin.set_fact:
    _mtv_migrations: "{{ _mtv_migrations | default([]) + [lookup('template', 'migration.yml.j2') | from_yaml] }}"
  loop: "{{ _mtv_plans_to_migrate }}"
  loop_control:
    loop_var: _mtv_plan_to_migrate

- name: _migrations | Create Migrations
  redhat.openshift.k8s:
    definition: "{{ _mtv_migrations }}"
    state: present
    apply: true
  register: migrations_create_result

- name: _migrations | Wait for Migrations
  when: _mtv_verify_migrations_complete|bool
  block:
    - name: _migrations | Check on Migrations
      kubernetes.core.k8s_info:
        api_version: "{{ created_migration.result.apiVersion }}"
        kind: "{{ created_migration.result.kind }}"
        name: "{{ created_migration.result.metadata.name }}"
        namespace: "{{ created_migration.result.metadata.namespace }}"
      register: created_migration_status
      loop_control:
        loop_var: created_migration
      loop: "{{ migrations_create_result.result.results if migrations_create_result.result is defined and 'results' in migrations_create_result.result else [migrations_create_result] }}" # noqa: yaml[line-length]
      failed_when:
        - created_migration_status is defined
        - "'resources' in created_migration_status"
        - created_migration_status.resources | length == 1
        - "'status' in created_migration_status.resources|first"
        - "'completed' in (created_migration_status.resources|first).status"
        - (created_migration_status.resources|first).status.completed | trim | length > 0
        - "'conditions' in (created_migration_status.resources|first).status"
        - (created_migration_status.resources|first).status.conditions | selectattr('type', 'defined') | selectattr('status', 'defined') | selectattr('type', 'equalto', 'Succeeded') | selectattr('status', 'equalto', 'True') | list | length == 0 # noqa: yaml[line-length]
      until:
        - created_migration_status is defined
        - "'resources' in created_migration_status"
        - created_migration_status.resources | length == 1
        - "'status' in created_migration_status.resources|first"
        - "'completed' in (created_migration_status.resources|first).status"
        - (created_migration_status.resources|first).status.completed | trim | length > 0
        - "'conditions' in (created_migration_status.resources|first).status"
        - (created_migration_status.resources|first).status.conditions | selectattr('type', 'defined') | selectattr('status', 'defined') | selectattr('type', 'equalto', 'Succeeded') | selectattr('status', 'equalto', 'True') | list | length == 1 # noqa: yaml[line-length]
      retries: 360
      delay: 20

...
