---

- name: _manage_secrets | Verify Secret Namespace and Name Provided
  ansible.builtin.assert:
    that:
      - ssh_secret['namespace'] | default("", true) | length > 0
      - ssh_secret['name'] | default("", true) | length > 0
    quiet: true
    fail_msg: Secret Namespace and Name must be provided

- name: _manage_secrets | Initialize SSH Keys Variables
  ansible.builtin.set_fact:
    vm_ssh_secret_keys: {}

- name: _manage_secrets | Manage Secret SSH Keys
  when: "'ssh_keys' in ssh_secret"
  ansible.builtin.include_tasks:
    file: _manage_secret_keys.yml
  loop: "{{ ssh_secret['ssh_keys'] | default([]) }}"
  loop_control:
    loop_var: ssh_key
    index_var: ssh_key_idx
    label: "key{{ ssh_key_idx + 1 }}"

- name: _manage_secrets | Create SSH Key Secret
  redhat.openshift.k8s: # noqa: fqcn[canonical]
    state: present
    api_key: "{{ vm_ssh_openshift_api_key }}"
    host: "{{ vm_ssh_openshift_host }}"
    validate_certs: "{{ vm_ssh_openshift_verify_ssl }}"
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ ssh_secret['name'] }}"
        namespace: "{{ ssh_secret['namespace'] }}"
      stringData: "{{ vm_ssh_secret_keys }}"
    apply: true
...
