---

- name: _process_machine_credential | Initialize Dynamic Map Variable
  ansible.builtin.set_fact:
    mapped_vars: {}

- name: _process_machine_credential | Map Credential File Contents
  when: aap_machine_credentials_input_map['src'] in aap_machine_credential
  ansible.builtin.include_tasks:
    file: _map_key_content.yml
  loop: "{{ aap_machine_credentials_input_maps }}"
  loop_control:
    loop_var: aap_machine_credentials_input_map
    label: "Mapping Credential Key '{{ aap_machine_credentials_input_map }}'"
  vars:
    map_src_var: "{{ aap_machine_credentials_input_map['src'] }}"
    map_dest_var: "{{ aap_machine_credentials_input_map['dest'] }}"

- name: _process_machine_credential | Render Machine Credential
  ansible.builtin.set_fact:
    _controller_credentials: "{{ _controller_credentials | default([]) + [lookup('ansible.builtin.template', 'machine_credential.yml.j2', template_vars=aap_machine_credentials_combined) | from_yaml] }}" # noqa: yaml[line-length]
  vars:
    aap_machine_credentials_combined: "{{ aap_machine_credential | ansible.builtin.combine(mapped_vars) }}"
...
